### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/draft-guide-microprofile-istio-retry-fallback#4]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux (Tested on Mac, @DannyS03 is responsible for the other OS tests)
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari (Used the `curl` command)
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases 

---

Test ran on MacOS, complete end-to-end.

- [x] include `MicroProfile` in the page-tags 

- [x] licence block missing from `start/../InventoryResource.java`, double check all other `.java` files to ensure they have the license blocks.

Deploying Istio
---
- [x] `Next, deploy Istio resources to your cluster by running the kubectl apply command, which creates or updates Kubernetes resources defined in a yaml file. This command deploys Istio.` 
"This command deploys istio is redundant since the start of the sentence states that you're deploying istio resources.

- [x] `Verify that Istio was successfully deployed. All the values in the AVAILABLE column will have a value of 1 after the deployment is complete.` Should change to `Verify that Istio was successfully deployed by running the following command:` and move the `All the values in the AVAILABLE column will have a value of 1 after the deployment is complete.` to after the command block for better flow.

- [x] Output of the `kubectl get deployments -n istio-system` command is different, see my output below:
```
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
grafana                  0/1     1            0           6s
istio-citadel            0/1     1            0           6s
istio-egressgateway      0/1     1            0           6s
istio-galley             0/1     1            0           6s
istio-ingressgateway     0/1     1            0           6s
istio-pilot              0/1     1            0           6s
istio-policy             0/1     1            0           6s
istio-sidecar-injector   0/1     1            0           6s
istio-telemetry          0/1     1            0           6s
istio-tracing            0/1     1            0           5s
kiali                    0/1     1            0           6s
prometheus               0/1     1            0           6s
```

- [x] The line `You don’t need to perform any additional steps for the sidecars to be injected.` seems unnecessary, and bloats the paragraph it is in.

Adding the MicroProfile @Retry annotation
---
- [x]  When telling the user to add the @Retry annotation, the @Fallback annotation also shows in the code pane, which doesn't exist in the `InventoryResource.java` file yet since the guide tells the user to add it in the later section. I suggest hiding this property in this section as well as any other related Fallback lines of code.
![image](https://user-images.githubusercontent.com/26514093/64277539-935cad80-cf18-11e9-9d29-9fd3f6f55903.png)

- [ ] Since the default number of retries for the `maxRetries` flag is 3, its redundant to include the flag just to set it to the default value. I understand it is for demonstration purposes but either use a different value or remove it entirely.

Building and running the application
---
- [x] `The above command returns 1, meaning that 1 request is made to the system service. Your single request to the service is successful with a 200 response code.` This sentence is unnecessarily long and repeats the same thing, I suggest making it more succinct, at the very least removing `The above command returns 1`

- [ ] Guide flow inconsistency, I recommend swapping the `Adding the MicroProfile @Retry` section with the `Building and running the application` section. Why do we talk about and implement the @Retry annotation if the next section shows the application running without issues? It would make sense to showcase the working application and then explaining the situation of the application failing, THEN introducing @Retry 

- [x] When using `curl` on the paused system pod, my error is `HTTP/1.1 503 Service Unavailable` instead of the guide `HTTP/1.1 503 Internal Server Error`

- [x] Maybe further explain why the number of retries is 37, since the @Retry annotation was set to the default number of retries of 3, so is the remaining 34 by MicroProfile?

Enabling Istio fault tolerance
---
- [x] Grammar inconsistency, if you capitalize each first letter in MicroProfile Fault Tolerance, the same should be applied to Istio Fault Tolerance, it is uncapitalized in multiple locations.

- [x] Specify that the `retries` field is located under the `route` spec in the updating of the `traffic.yaml` file.

- [ ] The hotspot includes an extra unnecessary blank line.
![image](https://user-images.githubusercontent.com/26514093/64284509-c195b980-cf27-11e9-8f43-fb9e340825ad.png)

- [ ] `The above command returns 60, indicating that a total of 60 requests are made to the system service. These requests include Istio’s default number of retries, the retries that you enabled in the traffic.yaml file, and the retries set by MicroProfile.` Same as comment above re: 1.

- [x] `You will disable some of MicroProfile’s capabilities, including Retry, to have your system service retry with only Istio’s Retry policy.` Reword, its awkward. Maybe try `Next, you will...` off the top of my head?

Turning off MicroProfile Fault Tolerance
---
- [x] Since the `ConfigMap` type doesn't exist in the `services.yaml` file, it would be a good idea to tell the user to add the object type first before talking about the fields/flags
![image](https://user-images.githubusercontent.com/26514093/64286538-b6448d00-cf2b-11e9-86a8-36b390d9ee57.png)

- [x] `The above command returns 15, indicating that a total of 15 requests are made to the system service. Since MicroProfile’s Retry policy is disabled, only Istio’s retries are performed.` Since Istio's retries was set to a max of 3, maybe explain why there resulted in 15 retries, this confused me.

Tearing down your environment
---
- [x] Reference the command blocks by stating `... by running the following command:` after the command description, i.e. `Delete your resources from the cluster, by running the following command:`, do this with all command blocks.

- [x] the result of the `kubectl label namespace default istio-injection-` command is shown below, it doesn't indicate that it was deleted... is this accurate?
![image](https://user-images.githubusercontent.com/26514093/64287874-cb6eeb00-cf2e-11e9-91d4-e99fd8cae973.png)

- [x] The flow here is confusing, maybe add a paragraph before the OS specific commands to explain that you need to run this to do something. It is slightly confusing to figure out that everyone is supposed to run the topmost command as well as their OS specific command
![image](https://user-images.githubusercontent.com/26514093/64288053-18eb5800-cf2f-11e9-8332-30d6aa42c24a.png)

**Comment by DannyS03** [comment]
**WINDOWS**

***Enabling MicroProfile Fault Tolerance***
- [ ] Need to wait before successful `200` response code is returned from the curl command; might want to consider mentioning the delay as the user would see an output of `0` when running the ```kubectl logs [system-pod-name] -c istio-proxy | grep -c system-service:9080``` command since the request would not have been actually been made.

![image](https://user-images.githubusercontent.com/25497083/64435722-fd985e00-d090-11e9-951a-86a5868448dd.png)

**Comment by MaiHameed** [comment]
Another note, instead of prompting the user to copy paste their [system-pod-name], you can use the following command to make it simpler -> `kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}' | grep system` see below:

![image](https://user-images.githubusercontent.com/26514093/64443892-e6fa0300-d0a0-11e9-9d6f-ab7e2bd9d7bc.png)

**Comment by NimG98** [comment]
UI issue for "the hotspot includes an extra unnecessary blank line":

https://github.com/OpenLiberty/openliberty.io/issues/1359
