### ISSUE TITLE
Consider microprofile-istio-retry-fallback as project ID

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-istio-retry-fallback#7]
Use microprofile-istio-retry-fallback as the ID and hence, guide-microprofile-istio-retry-fallback as the slug and repo name.  I believe this better conveys what we intend to show with this guide and is better for SEO too.

FYI, @gkwan-ibm.

**Comment by NimG98** [comment]
Commit for artifact id changes: https://github.com/OpenLiberty/draft-guide-microprofile-istio-retry-fallback/commit/c0cffefa7a945b2b88fd230c4405277fd32162ae
